# load critical packages 
library(mosaic)
library(tidyverse)
library(tidyr)
library(tidyselect)
library(ggpubr)
library(ggplot2)
library(rsample)
library(caret)
library(modelr)
library(parallel)
library(foreach)
library(stargazer)
library(knitr)